[sources.in]
type = "stdin"

[sinks.console]
inputs = ["in"]
type = "console"
encoding.codec = "json"

[sinks.tinybird]
inputs = ["in"]
type = "http"
uri = "https://api.us-east.tinybird.co/v0/events?name=test_ds&token=p.eyJ1IjogIjMwYWQ4YmE0LWE2NWQtNDYwYy1iNjY1LTg4MmQ1NTAyNjYyZCIsICJpZCI6ICIzMzMwNjY5ZC01YmUyLTRkYjEtOWE4OC04ZGJmZmRlYjJhODQiLCAiaG9zdCI6ICJ1c19lYXN0In0.JtmWpPC7VshMmzJrm-4REgsrUe2Y1jSgYw5u2Bd8zmE"
encoding.codec = "json"
encoding.only_fields = ["day", "total_click_agg_merge"]