[sources.in]
type = "stdin"

[sinks.upstash]
type = "kafka"
inputs = [ "to_metric" ]
bootstrap_servers = "sweeping-ant-9955-us1-kafka.upstash.io:9092"
topic = "clicks_aggregates"

[sinks.console]
inputs = ["parse"]
type = "console"
encoding.codec = "json"

[sinks.tinybird]
inputs = ["parse"]
type = "http"
uri = "https://api.us-east.tinybird.co/v0/events?name=agg_merge_tree_mv_count_0_mv_1&token=p.eyJ1IjogIjMwYWQ4YmE0LWE2NWQtNDYwYy1iNjY1LTg4MmQ1NTAyNjYyZCIsICJpZCI6ICIzMzMwNjY5ZC01YmUyLTRkYjEtOWE4OC04ZGJmZmRlYjJhODQiLCAiaG9zdCI6ICJ1c19lYXN0In0.JtmWpPC7VshMmzJrm-4REgsrUe2Y1jSgYw5u2Bd8zmE"
encoding.codec = "ndjson"
encoding.only_fields = ["day", "total_click_agg_merge"]