name: upstash_integration

on:
  workflow_dispatch:
    manual: true
  schedule:
    - cron: '*/10 * * * *'

jobs:
  datadog:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: sudo apt-get install --yes curl bc
    - run:  curl --proto '=https' --tlsv1.2 -sSfL https://sh.vector.dev | bash -s -- -y
    - run: ~/.vector/bin/vector --version
    - name: total_clicks_to_upstash
      run: |
        curl "https://api.us-east.tinybird.co/v0/pipes/agg_merge_tree_mv_count.ndjson?token=${TB_TOKEN}" | ~/.vector/bin/vector --config ./vector.toml
      env:
        TB_TOKEN: ${{ secrets.TB_TOKEN }}
